/*
Copyright 2018 Pusher Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	farosv1alpha1 "github.com/pusher/faros/pkg/apis/faros/v1alpha1"
	clientset "github.com/pusher/faros/pkg/client/clientset"
	internalinterfaces "github.com/pusher/faros/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/pusher/faros/pkg/client/listers/faros/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterGitTrackObjectInformer provides access to a shared informer and lister for
// ClusterGitTrackObjects.
type ClusterGitTrackObjectInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterGitTrackObjectLister
}

type clusterGitTrackObjectInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterGitTrackObjectInformer constructs a new informer for ClusterGitTrackObject type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterGitTrackObjectInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterGitTrackObjectInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterGitTrackObjectInformer constructs a new informer for ClusterGitTrackObject type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterGitTrackObjectInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FarosV1alpha1().ClusterGitTrackObjects().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FarosV1alpha1().ClusterGitTrackObjects().Watch(options)
			},
		},
		&farosv1alpha1.ClusterGitTrackObject{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterGitTrackObjectInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterGitTrackObjectInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterGitTrackObjectInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&farosv1alpha1.ClusterGitTrackObject{}, f.defaultInformer)
}

func (f *clusterGitTrackObjectInformer) Lister() v1alpha1.ClusterGitTrackObjectLister {
	return v1alpha1.NewClusterGitTrackObjectLister(f.Informer().GetIndexer())
}
