apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - faros.pusher.com
  resources:
  - gittracks
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - faros.pusher.com
  resources:
  - gittrackobjects
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - faros.pusher.com
  resources:
  - clustergittrackobjects
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - faros.pusher.com
  resources:
  - gittrackobjects
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
