/*
Copyright 2018 Pusher Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pusher/faros/pkg/apis/faros/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterGitTrackObjects implements ClusterGitTrackObjectInterface
type FakeClusterGitTrackObjects struct {
	Fake *FakeFarosV1alpha1
}

var clustergittrackobjectsResource = schema.GroupVersionResource{Group: "faros.pusher.com", Version: "v1alpha1", Resource: "clustergittrackobjects"}

var clustergittrackobjectsKind = schema.GroupVersionKind{Group: "faros.pusher.com", Version: "v1alpha1", Kind: "ClusterGitTrackObject"}

// Get takes name of the clusterGitTrackObject, and returns the corresponding clusterGitTrackObject object, and an error if there is any.
func (c *FakeClusterGitTrackObjects) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterGitTrackObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustergittrackobjectsResource, name), &v1alpha1.ClusterGitTrackObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterGitTrackObject), err
}

// List takes label and field selectors, and returns the list of ClusterGitTrackObjects that match those selectors.
func (c *FakeClusterGitTrackObjects) List(opts v1.ListOptions) (result *v1alpha1.ClusterGitTrackObjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustergittrackobjectsResource, clustergittrackobjectsKind, opts), &v1alpha1.ClusterGitTrackObjectList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterGitTrackObjectList{ListMeta: obj.(*v1alpha1.ClusterGitTrackObjectList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterGitTrackObjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterGitTrackObjects.
func (c *FakeClusterGitTrackObjects) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustergittrackobjectsResource, opts))
}

// Create takes the representation of a clusterGitTrackObject and creates it.  Returns the server's representation of the clusterGitTrackObject, and an error, if there is any.
func (c *FakeClusterGitTrackObjects) Create(clusterGitTrackObject *v1alpha1.ClusterGitTrackObject) (result *v1alpha1.ClusterGitTrackObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustergittrackobjectsResource, clusterGitTrackObject), &v1alpha1.ClusterGitTrackObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterGitTrackObject), err
}

// Update takes the representation of a clusterGitTrackObject and updates it. Returns the server's representation of the clusterGitTrackObject, and an error, if there is any.
func (c *FakeClusterGitTrackObjects) Update(clusterGitTrackObject *v1alpha1.ClusterGitTrackObject) (result *v1alpha1.ClusterGitTrackObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustergittrackobjectsResource, clusterGitTrackObject), &v1alpha1.ClusterGitTrackObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterGitTrackObject), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterGitTrackObjects) UpdateStatus(clusterGitTrackObject *v1alpha1.ClusterGitTrackObject) (*v1alpha1.ClusterGitTrackObject, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clustergittrackobjectsResource, "status", clusterGitTrackObject), &v1alpha1.ClusterGitTrackObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterGitTrackObject), err
}

// Delete takes name of the clusterGitTrackObject and deletes it. Returns an error if one occurs.
func (c *FakeClusterGitTrackObjects) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clustergittrackobjectsResource, name), &v1alpha1.ClusterGitTrackObject{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterGitTrackObjects) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustergittrackobjectsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterGitTrackObjectList{})
	return err
}

// Patch applies the patch and returns the patched clusterGitTrackObject.
func (c *FakeClusterGitTrackObjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterGitTrackObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustergittrackobjectsResource, name, pt, data, subresources...), &v1alpha1.ClusterGitTrackObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterGitTrackObject), err
}
