/*
Copyright 2018 Pusher Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/pusher/faros/pkg/apis/faros/v1alpha1"
	scheme "github.com/pusher/faros/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterGitTrackObjectsGetter has a method to return a ClusterGitTrackObjectInterface.
// A group's client should implement this interface.
type ClusterGitTrackObjectsGetter interface {
	ClusterGitTrackObjects() ClusterGitTrackObjectInterface
}

// ClusterGitTrackObjectInterface has methods to work with ClusterGitTrackObject resources.
type ClusterGitTrackObjectInterface interface {
	Create(*v1alpha1.ClusterGitTrackObject) (*v1alpha1.ClusterGitTrackObject, error)
	Update(*v1alpha1.ClusterGitTrackObject) (*v1alpha1.ClusterGitTrackObject, error)
	UpdateStatus(*v1alpha1.ClusterGitTrackObject) (*v1alpha1.ClusterGitTrackObject, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterGitTrackObject, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterGitTrackObjectList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterGitTrackObject, err error)
	ClusterGitTrackObjectExpansion
}

// clusterGitTrackObjects implements ClusterGitTrackObjectInterface
type clusterGitTrackObjects struct {
	client rest.Interface
}

// newClusterGitTrackObjects returns a ClusterGitTrackObjects
func newClusterGitTrackObjects(c *FarosV1alpha1Client) *clusterGitTrackObjects {
	return &clusterGitTrackObjects{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterGitTrackObject, and returns the corresponding clusterGitTrackObject object, and an error if there is any.
func (c *clusterGitTrackObjects) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterGitTrackObject, err error) {
	result = &v1alpha1.ClusterGitTrackObject{}
	err = c.client.Get().
		Resource("clustergittrackobjects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterGitTrackObjects that match those selectors.
func (c *clusterGitTrackObjects) List(opts v1.ListOptions) (result *v1alpha1.ClusterGitTrackObjectList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterGitTrackObjectList{}
	err = c.client.Get().
		Resource("clustergittrackobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterGitTrackObjects.
func (c *clusterGitTrackObjects) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clustergittrackobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterGitTrackObject and creates it.  Returns the server's representation of the clusterGitTrackObject, and an error, if there is any.
func (c *clusterGitTrackObjects) Create(clusterGitTrackObject *v1alpha1.ClusterGitTrackObject) (result *v1alpha1.ClusterGitTrackObject, err error) {
	result = &v1alpha1.ClusterGitTrackObject{}
	err = c.client.Post().
		Resource("clustergittrackobjects").
		Body(clusterGitTrackObject).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterGitTrackObject and updates it. Returns the server's representation of the clusterGitTrackObject, and an error, if there is any.
func (c *clusterGitTrackObjects) Update(clusterGitTrackObject *v1alpha1.ClusterGitTrackObject) (result *v1alpha1.ClusterGitTrackObject, err error) {
	result = &v1alpha1.ClusterGitTrackObject{}
	err = c.client.Put().
		Resource("clustergittrackobjects").
		Name(clusterGitTrackObject.Name).
		Body(clusterGitTrackObject).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterGitTrackObjects) UpdateStatus(clusterGitTrackObject *v1alpha1.ClusterGitTrackObject) (result *v1alpha1.ClusterGitTrackObject, err error) {
	result = &v1alpha1.ClusterGitTrackObject{}
	err = c.client.Put().
		Resource("clustergittrackobjects").
		Name(clusterGitTrackObject.Name).
		SubResource("status").
		Body(clusterGitTrackObject).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterGitTrackObject and deletes it. Returns an error if one occurs.
func (c *clusterGitTrackObjects) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clustergittrackobjects").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterGitTrackObjects) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clustergittrackobjects").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterGitTrackObject.
func (c *clusterGitTrackObjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterGitTrackObject, err error) {
	result = &v1alpha1.ClusterGitTrackObject{}
	err = c.client.Patch(pt).
		Resource("clustergittrackobjects").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
