/*
Copyright 2018 Pusher Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/pusher/faros/pkg/apis/faros/v1alpha1"
	scheme "github.com/pusher/faros/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterGitTracksGetter has a method to return a ClusterGitTrackInterface.
// A group's client should implement this interface.
type ClusterGitTracksGetter interface {
	ClusterGitTracks() ClusterGitTrackInterface
}

// ClusterGitTrackInterface has methods to work with ClusterGitTrack resources.
type ClusterGitTrackInterface interface {
	Create(*v1alpha1.ClusterGitTrack) (*v1alpha1.ClusterGitTrack, error)
	Update(*v1alpha1.ClusterGitTrack) (*v1alpha1.ClusterGitTrack, error)
	UpdateStatus(*v1alpha1.ClusterGitTrack) (*v1alpha1.ClusterGitTrack, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterGitTrack, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterGitTrackList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterGitTrack, err error)
	ClusterGitTrackExpansion
}

// clusterGitTracks implements ClusterGitTrackInterface
type clusterGitTracks struct {
	client rest.Interface
}

// newClusterGitTracks returns a ClusterGitTracks
func newClusterGitTracks(c *FarosV1alpha1Client) *clusterGitTracks {
	return &clusterGitTracks{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterGitTrack, and returns the corresponding clusterGitTrack object, and an error if there is any.
func (c *clusterGitTracks) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterGitTrack, err error) {
	result = &v1alpha1.ClusterGitTrack{}
	err = c.client.Get().
		Resource("clustergittracks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterGitTracks that match those selectors.
func (c *clusterGitTracks) List(opts v1.ListOptions) (result *v1alpha1.ClusterGitTrackList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterGitTrackList{}
	err = c.client.Get().
		Resource("clustergittracks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterGitTracks.
func (c *clusterGitTracks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clustergittracks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterGitTrack and creates it.  Returns the server's representation of the clusterGitTrack, and an error, if there is any.
func (c *clusterGitTracks) Create(clusterGitTrack *v1alpha1.ClusterGitTrack) (result *v1alpha1.ClusterGitTrack, err error) {
	result = &v1alpha1.ClusterGitTrack{}
	err = c.client.Post().
		Resource("clustergittracks").
		Body(clusterGitTrack).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterGitTrack and updates it. Returns the server's representation of the clusterGitTrack, and an error, if there is any.
func (c *clusterGitTracks) Update(clusterGitTrack *v1alpha1.ClusterGitTrack) (result *v1alpha1.ClusterGitTrack, err error) {
	result = &v1alpha1.ClusterGitTrack{}
	err = c.client.Put().
		Resource("clustergittracks").
		Name(clusterGitTrack.Name).
		Body(clusterGitTrack).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterGitTracks) UpdateStatus(clusterGitTrack *v1alpha1.ClusterGitTrack) (result *v1alpha1.ClusterGitTrack, err error) {
	result = &v1alpha1.ClusterGitTrack{}
	err = c.client.Put().
		Resource("clustergittracks").
		Name(clusterGitTrack.Name).
		SubResource("status").
		Body(clusterGitTrack).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterGitTrack and deletes it. Returns an error if one occurs.
func (c *clusterGitTracks) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clustergittracks").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterGitTracks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clustergittracks").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterGitTrack.
func (c *clusterGitTracks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterGitTrack, err error) {
	result = &v1alpha1.ClusterGitTrack{}
	err = c.client.Patch(pt).
		Resource("clustergittracks").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
