/*
Copyright 2018 Pusher Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/pusher/faros/pkg/apis/faros/v1alpha1"
	scheme "github.com/pusher/faros/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GitTrackObjectsGetter has a method to return a GitTrackObjectInterface.
// A group's client should implement this interface.
type GitTrackObjectsGetter interface {
	GitTrackObjects(namespace string) GitTrackObjectInterface
}

// GitTrackObjectInterface has methods to work with GitTrackObject resources.
type GitTrackObjectInterface interface {
	Create(*v1alpha1.GitTrackObject) (*v1alpha1.GitTrackObject, error)
	Update(*v1alpha1.GitTrackObject) (*v1alpha1.GitTrackObject, error)
	UpdateStatus(*v1alpha1.GitTrackObject) (*v1alpha1.GitTrackObject, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GitTrackObject, error)
	List(opts v1.ListOptions) (*v1alpha1.GitTrackObjectList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitTrackObject, err error)
	GitTrackObjectExpansion
}

// gitTrackObjects implements GitTrackObjectInterface
type gitTrackObjects struct {
	client rest.Interface
	ns     string
}

// newGitTrackObjects returns a GitTrackObjects
func newGitTrackObjects(c *FarosV1alpha1Client, namespace string) *gitTrackObjects {
	return &gitTrackObjects{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gitTrackObject, and returns the corresponding gitTrackObject object, and an error if there is any.
func (c *gitTrackObjects) Get(name string, options v1.GetOptions) (result *v1alpha1.GitTrackObject, err error) {
	result = &v1alpha1.GitTrackObject{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gittrackobjects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GitTrackObjects that match those selectors.
func (c *gitTrackObjects) List(opts v1.ListOptions) (result *v1alpha1.GitTrackObjectList, err error) {
	result = &v1alpha1.GitTrackObjectList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gittrackobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gitTrackObjects.
func (c *gitTrackObjects) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gittrackobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a gitTrackObject and creates it.  Returns the server's representation of the gitTrackObject, and an error, if there is any.
func (c *gitTrackObjects) Create(gitTrackObject *v1alpha1.GitTrackObject) (result *v1alpha1.GitTrackObject, err error) {
	result = &v1alpha1.GitTrackObject{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gittrackobjects").
		Body(gitTrackObject).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gitTrackObject and updates it. Returns the server's representation of the gitTrackObject, and an error, if there is any.
func (c *gitTrackObjects) Update(gitTrackObject *v1alpha1.GitTrackObject) (result *v1alpha1.GitTrackObject, err error) {
	result = &v1alpha1.GitTrackObject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gittrackobjects").
		Name(gitTrackObject.Name).
		Body(gitTrackObject).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *gitTrackObjects) UpdateStatus(gitTrackObject *v1alpha1.GitTrackObject) (result *v1alpha1.GitTrackObject, err error) {
	result = &v1alpha1.GitTrackObject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gittrackobjects").
		Name(gitTrackObject.Name).
		SubResource("status").
		Body(gitTrackObject).
		Do().
		Into(result)
	return
}

// Delete takes name of the gitTrackObject and deletes it. Returns an error if one occurs.
func (c *gitTrackObjects) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gittrackobjects").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gitTrackObjects) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gittrackobjects").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gitTrackObject.
func (c *gitTrackObjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitTrackObject, err error) {
	result = &v1alpha1.GitTrackObject{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gittrackobjects").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
